### ISSUE TITLE
Error when processing the data

### ISSUE THREAD

**Issue by LaLaLailalai** [lisiyao21/Bailando#10]
Hi,

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/16380906/165940588-2690d71d-ac27-4cd0-9dbe-2124796e0559.png">
The index of the preprocessing code "_prepro_aistpp.py" seems to be wrong, cause there is no such file in the folder.
Do you know how to fix it?

**Comment by lisiyao21** [comment]
Yes I know. 
This is caused by the last line of the split txt file which doesn't contain an '\n' and the last digit was filterd. You could add addtional ones to them.
I will also make an update today. I am sorry for troubling you. Thank you for your patience and for your interest~

**Comment by LaLaLailalai** [comment]
> 

Thanks! I already fixed it by changing train[-1] and test[-1] to the right file name.

**Comment by lisiyao21** [comment]
Guys, please note that I have make an update. PLEASE DO NOTE that the original paper test on validation (20) and test (20) sets both. This was done by hard code when I did but it only processed test set in your version . Please re-process the data using new code. Otherwise, the test results can be different~

**Comment by lisiyao21** [comment]
> Guys, please note that I have make an update. PLEASE DO NOTE that the original paper test on validation (20) and test (20) sets both. This was done by hard code when I did but it only processed test set in your version . Please re-process the data using new code. Otherwise, the test results can be different~

@LaLaLailalai @kevink2424

**Comment by kevink2424** [comment]
@lisiyao21  Thank you !
