### ISSUE TITLE
When will release the  'Choreographic for music in the wild' function

### ISSUE THREAD

**Issue by kevink2424** [lisiyao21/Bailando#12]

**Comment by zhangsanfeng86** [comment]
@lisiyao21  
Hi siyao,  
Same question, when release  'Choreographic for music in the wild' ?

**Comment by lisiyao21** [comment]
Hi Hi. Sorry for late reply. Choreography for wild music is just a stage of actor critic finetuning using your given music. I am afraid of bugs for this version of code so I prepare to test it. Just this weekend!

**Comment by zhangsanfeng86** [comment]
look forward！！！

**Comment by kevink2424** [comment]
I set up a wechat group for discussion. I hope you can join in. I'll set you as the group leader.   @lisiyao21 
![image](https://user-images.githubusercontent.com/73547638/167062791-d0a9013a-9ca8-4633-8358-fec716d61f49.png)

**Comment by lisiyao21** [comment]
> I set up a wechat group for discussion. I hope you can join in. I'll set you as the group leader. @lisiyao21
> 
> <img alt="image" width="343" src="https://user-images.githubusercontent.com/97677638/167063008-6cadf52b-2836-4227-ba38-910606d89530.png">

Sorry long time no reply. Could you send this QR code again for me?

**Comment by zhangsanfeng86** [comment]
@lisiyao21  welcome

<img width="395" alt="image" src="https://user-images.githubusercontent.com/73547638/170285664-bd49ac1f-ed31-4db4-ae36-82a4539613d3.png">

**Comment by chamecall** [comment]
Hello. Are there any updates on choreographic for music in the wild?
Thanks in advance.

**Comment by lisiyao21** [comment]
> Hello. Are there any updates on choreographic for music in the wild? Thanks in advance.

I have made an update. Try it~

**Comment by aleeyang** [comment]
> @lisiyao21 welcome
> 
> <img alt="image" width="351" src="https://user-images.githubusercontent.com/73547638/170286030-ae7b04de-23fe-4e58-9fe9-92389d01b237.png">

Can you share the QR code again?

**Comment by WyattYun** [comment]
I want to join the discussion, too. Could you share the QR code of wechat group again, please?

**Comment by DonlynLee** [comment]
Hi, I want to join the Wechat group, too. Could you please share the QR code again? Thank you !
