### ISSUE TITLE
Why extracting audio features twice with different sampling rate? 

### ISSUE THREAD

**Issue by XiSHEN0220** [lisiyao21/Bailando#14]
Hi, Siyao~ 
Thanks for releasing and cleaning the code!! 

May I ask why in the pre-processing part, the audio (music) features are extracted twice and with different sampling rates? 

Precisely, in [_prepro_aistpp.py](https://github.com/lisiyao21/Bailando/blob/main/_prepro_aistpp.py#L116), the audio features are extracted with the sampling rate [15360*2](https://github.com/lisiyao21/Bailando/blob/main/_prepro_aistpp.py#L32)

While in [_prepro_aistpp_music.py](https://github.com/lisiyao21/Bailando/blob/main/_prepro_aistpp_music.py#L58), the audio features are extracted with the sampling rate [15360*2/8](https://github.com/lisiyao21/Bailando/blob/main/_prepro_aistpp_music.py#L23)

**Comment by lisiyao21** [comment]
> Hi, Siyao~ Thanks for releasing and cleaning the code!!
> 
> May I ask why in the pre-processing part, the audio (music) features are extracted twice and with different sampling rates?
> 
> Precisely, in [_prepro_aistpp.py](https://github.com/lisiyao21/Bailando/blob/main/_prepro_aistpp.py#L116), the audio features are extracted with the sampling rate [15360*2](https://github.com/lisiyao21/Bailando/blob/main/_prepro_aistpp.py#L32)
> 
> While in [_prepro_aistpp_music.py](https://github.com/lisiyao21/Bailando/blob/main/_prepro_aistpp_music.py#L58), the audio features are extracted with the sampling rate [15360*2/8](https://github.com/lisiyao21/Bailando/blob/main/_prepro_aistpp_music.py#L23)

Sorry for replying late.

The initial idea is to fit the frame rate of both the dancing sequence (15360*2 --> 60fps) and the downsampled features (15360*2/8 -->7.5fps). In motion gpt training we need to feed 7.5fps music feature to align with the motion code (downsampled 8 times from original dance) while in reinforcement learning, we need to count in original dance (60fps). So we made the feature twice.

Hope this help.

**Comment by XiSHEN0220** [comment]
Thanks ~

**Comment by zhangsanfeng86** [comment]
> 

Hi @lisiyao21 
----------------------------
downsampled 8 times from original dance
----------------------------
Could you show where is the code "downsampled 8 times from original dance"?
my trainingdata is 30fps， so I want to downsampled 4 times.

**Comment by KevinGoodman** [comment]
@XiSHEN0220 @lisiyao21 Could you please tell me why use 15360 * 2 as the sampling rate for 60 FPS, I mean, how this specific rate is obtained through calculation?

**Comment by Sun-Happy-YKX** [comment]
> 15360_2 _

I have set the sample rate as 15360*2, and use you provided function "extract_acoustic_feature", but the fps of  extracted is not 60, as follow, can you give me some suggestions?
![image](https://github.com/lisiyao21/Bailando/assets/50354191/70b4fb2f-b5df-45ce-a187-4f8b31220bdb)
