### ISSUE TITLE
about the run command

### ISSUE THREAD

**Issue by aleeyang** [lisiyao21/Bailando#24]
For me, a beginner of DL,
`sh srun.sh configs/sep_vqvae.yaml train [your node name] 1`
what dose the '[your node name]' mean? 
can you give me a more specific command?
Thank you a lot!

**Comment by KevinGoodman** [comment]
I have the same problem, could you please share your solution?

**Comment by Xianjin111** [comment]
> I have the same problem, could you please share your solution?

Do you know how to deal with it?  I'm also confused about it.

**Comment by DonlynLee** [comment]
I have the same problem, have you solved it?
