### ISSUE TITLE
about the data process

### ISSUE THREAD

**Issue by pengc02** [lisiyao21/Bailando#33]
Hello siyao!
I'm reading your code and i'm confused about the 'align' function in '_prepro_aistpp.py'.
To make the length(time) of music equal to that of dance, you throw the extra feature away. Is that reasonable? Why not do a uniform sampling?
Sorry for bothering you. 
![image](https://user-images.githubusercontent.com/71554280/185394556-77a527f7-b9c9-4074-a83e-8a11241921e3.png)

**Comment by Sun-Happy-YKX** [comment]
hello, I have met the same problem, could you please share how to sovle this problem?
