### ISSUE TITLE
data lost

### ISSUE THREAD

**Issue by pengc02** [lisiyao21/Bailando#34]
Your pre-processed data lost gPO_sBM_cAll_d10_mPO0_ch06, which made me confused.

**Comment by lisiyao21** [comment]
Sorry for late reply and the inconvinience! I am checking about that. Soon will reply you.

**Comment by lisiyao21** [comment]
Thank you for indicating that! This one is missed in the released zip file. It is because 'gPO_sBM_cAll_d10_mPO0_ch06' is in the last line of train/split files and the preprocess scripts (revised for release) of data omitted it. I will soon added it up.

However,  'gPO_sBM_cAll_d10_mPO0_ch06' is included in the data in our cluster. So, the released pretraining weights are correct.

**Comment by lisiyao21** [comment]
Hi. I have added 'gPO_sBM_cAll_d10_mPO0_ch06.json' into the zip file.

**Comment by RobinWitch** [comment]
@lisiyao21 Hi Siyao ,I meet the same problem too ,will you fix it ?

> Hi Siyao, it seems like 'gPO_sBM_cAll_d10_mPO0_ch06.json' in the latest release zip is an empty file, which causes error.

**Comment by dsdf783** [comment]
Hi siyao,
     'gPO_sBM_cAll_d10_mPO0_ch06.json' in data.zip is still  empty can can you solve this problem?

**Comment by DonlynLee** [comment]
I have the same problem, I deleted the 'gPO_sBM_cAll_d10_mPO0_ch06.json' to solve the error, but it seems like when I run the evaluation stage, the code is stuck at the step 'Generating Images' and there is no result. Do you have any ideas?

**Comment by lisiyao21** [comment]
Hi guys, so sorry for such a late reply. I don't know why the file is not uploaded. Here is a separate link :https://drive.google.com/file/d/1G31GqKCQAxn2NnXxGY9_vAVEeZnW2uZd/view?usp=sharing

**Comment by lisiyao21** [comment]
Actually you can directly delete the blank file. It won't lead to too much difference I think.

**Comment by lisiyao21** [comment]
> I have the same problem, I deleted the 'gPO_sBM_cAll_d10_mPO0_ch06.json' to solve the error, but it seems like when I run the evaluation stage, the code is stuck at the step 'Generating Images' and there is no result. Do you have any ideas?

I think it is on validation for each 20 epcohs, but won't stuck too long. Otherwise there could be a problem

**Comment by UsanoCoCr** [comment]
Hi siyao,
The separate link you provided seems to be 'gPO_sBM_cAll_d10_mPO3_ch06.json' rather than 'gPO_sBM_cAll_d10_mPO0_ch06.json', can you re-provide the correct one?
