### ISSUE TITLE
 Supplementary File

### ISSUE THREAD

**Issue by sduGuyu** [lisiyao21/Bailando#44]
I noticed that you mentioned the  supplementary file many times, including the  detailed derivation of L_AC,  the structures of the convolutional encoder and decoders, and so on...
Where can I find it? I have searched on your website but not found it.

**Comment by lisiyao21** [comment]
Hi! Thanks so much for your interest. Please find the supplementary file in the CVPR repository: https://openaccess.thecvf.com/content/CVPR2022/html/Siyao_Bailando_3D_Dance_Generation_by_Actor-Critic_GPT_With_Choreographic_Memory_CVPR_2022_paper.html

**Comment by sduGuyu** [comment]
Thanks for your wonderful work and sharing!
