### ISSUE TITLE
No such file or directory: '/mnt/lustre/share/lisiyao1/original_videos/aistpp-audio/'

### ISSUE THREAD

**Issue by donghaoye** [lisiyao21/Bailando#5]
Bailando/utils/functional.py", line 130, in img2video
    music_names = sorted(os.listdir(audio_dir))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/lustre/share/lisiyao1/original_videos/aistpp-audio/'

**Comment by lisiyao21** [comment]
I have removed this hard code. Could you please try again?
